import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import GoogleButton from "../components/button/googleButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Simple-Art
            <GoogleButton></GoogleButton>
        </h1>

        <p className={styles.description}>
          A drawing a day
        </p>

        <div className={styles.grid}>
          <Link href="/dailyart">
            <a className={styles.card}>
                <h2>Daily Art &rarr;</h2>
                <p>Previous Simple-Art available on the marketplace.</p>
            </a>
          </Link>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Exclusive Art &rarr;</h2>
            <p>Become the exclusive owner, if bought by the end of the day. Only one available.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>How it works &rarr;</h2>
            <p>Discover how you can be part of the Simple-Art community.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Gallery &rarr;</h2>
            <p>
              View current owners of exclusive Simple-Art
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
